### PR TITLE
adding version 3.2.20230711

### PR DESCRIPTION
**Pull request by erinyoung**
PR for version 3.2.20230711

### CODE REVIEW

**Comment by jwarnn** [comment]
Is this [3.2.20230711 - 2](https://github.com/UPHL-BioNGS/Grandeur/releases/tag/v3.2.20230711-2) or [3.2.20230711](https://github.com/UPHL-BioNGS/Grandeur/releases/tag/v3.2.20230711)?

**Comment by erinyoung** [comment]
[3.2.20230711 - 2](https://github.com/UPHL-BioNGS/Grandeur/releases/tag/v3.2.20230711-2)

**Comment by jwarnn** [comment]
I am testing it on ICA now with a little dataset then I will do a recent run. If all looks well I will approve.

**Comment by jwarnn** [comment]
The summary scripts failed to generate in the second test. It similiar issue we had been seeing before on ICA but on the test it was the 'quast' file that caused pandas errors and I have seen multi-qc file do the same thing. I will look at the summary.py file and see if there is a way to make it more robust to errors.

**Comment by erinyoung** [comment]
I'll look into the quast error.

**Comment by erinyoung** [comment]
It looks like the header gets lost when there are failed samples. Failed samples pass through first and set the header.
```
==> grandeur/quast/NTC-UT-M70330-230710/transposed_report.tsv <==

==> grandeur/quast/PNUSAV004034-UT-M70330-230710/transposed_report.tsv <==
sample	Assembly	# contigs (>= 0 bp)	# contigs (>= 1000 bp)	# contigs (>= 5000 bp)	# contigs (>= 10000 bp)	# contigs (>= 25000 bp)	# contigs (>= 50000 bp)	Total length (>= 0 bp)	Total length (>= 1000 bp)	Total length (>= 5000 bp)	Total length (>= 10000 bp)	Total length (>= 25000 bp)	Total length (>= 50000 bp)	# contigs	Largest contig	Total length	GC (%)	N50	N75	L50	L75	# N's per 100 kbp
PNUSAV004034-UT-M70330-230710	PNUSAV004034_UT_M70330_230710_contigs	132	48	31	28	26	21	5140512	5111281	5069128	5051477	5017457	4818483	61	691582	5120399	45.28	461907	137998	5	10	0.00

==> grandeur/quast/PNUSAV004035-UT-M70330-230710/transposed_report.tsv <==
sample	Assembly	# contigs (>= 0 bp)	# contigs (>= 1000 bp)	# contigs (>= 5000 bp)	# contigs (>= 10000 bp)	# contigs (>= 25000 bp)	# contigs (>= 50000 bp)	Total length (>= 0 bp)	Total length (>= 1000 bp)	Total length (>= 5000 bp)	Total length (>= 10000 bp)	Total length (>= 25000 bp)	Total length (>= 50000 bp)	# contigs	Largest contig	Total length	GC (%)	N50	N75	L50	L75	# N's per 100 kbp
PNUSAV004035-UT-M70330-230710	PNUSAV004035_UT_M70330_230710_contigs	186	164	134	118	77	30	5195620	5185407	5106040	4982845	4223143	2442130	172	154783	5191143	45.29	48142	33514	34	66	0.00
```

**Comment by erinyoung** [comment]
The release tomorrow should have the fix needed

**Pull request closed without merging**
