### PR TITLE
adding grandeur 3.1.20230414

### PR DESCRIPTION
**Pull request by erinyoung**
This version has emmtyping

### CODE REVIEW

**Comment by jwarnn** [comment]
Sorry I didn't see this PR until today. I have done a small test that worked with no modifications. I am doing a full ran of samples, UT-M03999-230504, which I will compare to the results on the nas.

**Review by jwarnn — APPROVED** [review]
All the results and expected files are as expected. I could not find a results file on the NAS that matched the one on ICA but while looking into that it looks like all scripts are working as intended and all information is available. I think it is because the versions are different the nextflow.log for that run says v1.0.20220106 but that seems a little old. I think the process you are using to convert Granduear versions into versions that can run on ICA is working.

**Comment by jwarnn** [comment]
I am not sure if we want to merge this pull request because I took so long to do this review there is a new version of Grandeur already released; v3.1.20230509. What do you think?

**Comment by erinyoung** [comment]
Yeah. We might want to wait until it's finally approved.

**Comment by erinyoung** [comment]
I just added [3.1.20230509](https://github.com/UPHL-BioNGS/ICA_Modified_Nextflow_Scripts/pull/16/commits/d9daad6938e7837cdcc0ee66f08ce830a9fef38d)

**Comment by erinyoung** [comment]
I think we can ignore the prior versions. Are the mash and everything still accurate?

**Comment by jwarnn** [comment]
I have ref sec 217 on the production project of ICA.

**Comment by jwarnn** [comment]
I compared a run from the linux station to a run from ICA the results were the same. I am merging this PR.

**Pull request merged**
