### PR TITLE
added in cpus and updated containers

### PR DESCRIPTION
**Pull request by erinyoung**
Mostly what I did was went through each module and
- added cpu, and publishDir information
- standardized process syntax (to make my nextflow linter happy)
- updated some of the container versions
- removed most 'when' statements

I downsized the instance for a few containers

I also removed phylogenetic analysis, which is probably going to break something.

### CODE REVIEW

**Comment by jwarnn** [comment]
I should of pointed this out to you before but you should read this line in https://help.ica.illumina.com/project/p-flow/f-pipelines. "Daemon sets and system processes consume approximately 1CPU and 2GB Mem from the base values shown in the table. Consumption will vary based on the activity of the pod." So for 'standard-small' the CPUs need to be 1 instead of 2.

**Comment by jwarnn** [comment]
This is also more of a Nextflow thing but since we can't run a -resume on any of the analyses I have used ```errorStrategy { task.attempt < 4 ? 'retry' : 'ignore'} ```.

**Comment by erinyoung** [comment]
I think I have included an 
```
errorStrategy { task.attempt < 3 ? 'retry' : 'ignore'}
```
to each process. Could really be `task.attempt < 2`.

No longer using `standard-small`. bbduk, spades, kraken2, and fastani may still crash due to resource management issues, but I'm willing to risk it.

**Comment by erinyoung** [comment]
I just tried to run this locally, and it looks like I do need to add back in the processes params to main.nf. 

I'm going to convert this to a draft until those issues are resolved.

**Comment by erinyoung** [comment]
Grandeur has changed to the point that this doesn't matter anymore. I'm closing this.

**Pull request closed without merging**
